### ISSUE TITLE
Error with do_umount() invocation

### ISSUE THREAD

**Issue by ephestione** [dolorosus/RaspiBackup#1]
Anyway I try to start the backup (I first tried with the commandline I was using with lzkelley's build) I always get:
```
sudo ./backup start -ci /dev/sdb -s 4000  /media/giant/_PiBackup/$(uname -n)-$(date +%Y-%m-%d).img
./backup: line 321: syntax error near unexpected token `>'
./backup: line 321: `   do_umount() 
```

I tried with the basic sintax:
`sudo ./backup start -c  /media/giant/_PiBackup/test.img`
but that doesn't solve it

If I comment like so:
`do_umount() # > /dev/null 2>&1'`
I then get 
```
./backup: line 322: syntax error near unexpected token `truncate'
./backup: line 322: `   truncate --size=+1G "${IMAGE}"'

and at this point I'm pretty lost since I cannot reverse engineer the code right now :smile: 
```

**Comment by ephestione** [comment]
D'oh, solved it by comparing with other do_umount invocations, there shouldn't be "()" there, just do_umount > /dev/null 2>&1, and same in second invocation inside do_resize()

**Comment by dolorosus** [comment]
Corrected!
Thanks for finding this typo
