### ISSUE TITLE
FR: cloud upload

### ISSUE THREAD

**Issue by ephestione** [dolorosus/RaspiBackup#11]
Comes after 7zip compression, for obvious reasons.
There is already a github repo of a stable dropbox uploader, which I use for my bazidrop repo, and I remember seeing somewhere similar tools for mega.

**Comment by dolorosus** [comment]
I would prefer to use another script for compression and upload to online destination.
One script one task!
also take a look at:
https://github.com/dolorosus/RaspiBackup/issues/10#issuecomment-537504596

**Comment by ephestione** [comment]
I can dig that, especially since you don't need it given your configuration
