### ISSUE TITLE
No space left on device (28)

### ISSUE THREAD

**Issue by JoostDkr** [dolorosus/RaspiBackup#17]
I Placed RaspiBackup in ./pi/scripts and run ik manualy by my own bash file with a content of:
_#!/bin/bash
_sdkaart_pd=/media/pi/RpiBackup
_sudo ./scripts/RaspiBackup.sh start -c $sdkaart_pd/backup.img___

The only error I get is:
No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(374) [receiver=3.1.3]

For more info from the RaspiBackup.out: [t2.txt](https://github.com/user-attachments/files/17229241/t2.txt)

I changed line 519 the 500 in 3000. (Don't know if this is the right place to enlarge the image...). The result was no error anymore, but after writing the image to a sd-card with win23diskmanager (windows) the raspberry did not work properly.

(I spend a lot of time to get working RaspiBackup properly, still without success.)
What am I doing  wrong?

**Comment by dolorosus** [comment]
It is a bad idea to change the source code of a script without understanding how the script works. Due to changing the script this BACKUPFILE isn't useable anymore.

Revert all changes you've done and start a backup from scratch. 

- Delete the BACKUPFILE 
- Start an initial backup ```RaspiBackup.sh start -c BACKUPFILE```. This will create a backupfile with appr. 1000Mb free space for subsequent backups. The automatic calculation should work in most cases.
- If you ran into a "No space left on device" error, don't panic! Just use the ```resize``` command to resize the BACKUPFILE. ```RaspiBackup.sh resize BACKUPFILE``` will add 1000Mb to your Backupfile.  After resizing you can restart the backup to your BACKUPFILE ```RaspiBackup.sh start BACKUPFILE```. 
- 

You can check the freespace in your BACKUPFILE using ```RaspiBackup.sh showdf BACKUPFILE``` .
Examples are given in ```readme.md```.

**Comment by JoostDkr** [comment]
i'm using a target sd-card of 32Gb. File system Exfat(On window formatted)
Updated Rasbian; Raspberry rebooted; backup.img deleted

These were my commands:

pi@Raspberrypi-2:~ $ lsblk
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0         7:0    0  9.7G  0 loop
├─loop0p1   259:0    0  546M  0 part
└─loop0p2   259:1    0  9.1G  0 part /mnt/backup.img
sda           8:0    1 29.7G  0 disk
└─sda1        8:1    1 29.7G  0 part /media/pi/rpi-backup
mmcblk0     179:0    0 29.7G  0 disk
├─mmcblk0p1 179:1    0  546M  0 part /boot
└─mmcblk0p2 179:2    0 10.3G  0 part /

sudo mkdir /media/pi/rpi-backup
sudo mount /dev/sda1 /media/pi/rpi-backup
sudo RaspiBackup.sh -c /media/pi/rpi-backup
RaspiBackup gives a error:
[RaspiBackup.txt](https://github.com/user-attachments/files/17249348/RaspiBackup.txt)

  rsync: write failed on "/mnt/backup.img/var/swap": No space left on device (28)
  rsync error: error in file IO (code 11) at receiver.c(374) [receiver=3.1.3]

sudo ./scripts/RaspiBackup.sh resize /media/pi/rpi-backup/backup.img
This gave errors: 
[RaspiBackup2.txt](https://github.com/user-attachments/files/17249349/RaspiBackup2.txt)

 invalid option -- 'f'
 The filesystem is already 2397440 (4k) blocks long.  Nothing to do!

I have tried a lot. But without succes :-(

**Comment by dolorosus** [comment]
Looks strange...

It looks as if the calculation of the free space is too strongly adapted to Bookworm. I have created a branch 'spacetest' with a more generous free space calculation. The initial backup should work with this in any case.

Can you please test a backup with the script from the 'spacetest' branch?

The message when resizing (`parted: invalid option -- 'f'`) is confusing. I was able to work with the script under Bullseye without any problems. 

Which Operating System gives  `hostnamectl`?
Which version of `parted` are you using (`parted --version`)?

**Comment by JoostDkr** [comment]
OK, I have run the spacetest-version.  [RaspiBackup3.txt](https://github.com/user-attachments/files/17257356/RaspiBackup3.txt)
I  discovered one error: "partx: /dev/loop0: error adding partitions 1-2"
I started the rpi with the generated backup.img.
Putty works ok 
Domoticz works OK.
The remote desktop does not work :-(
  It uses xrdp
   "systemctl is-active xrdp" results in "failed". It should be "active"

**Comment by dolorosus** [comment]
I've no clue regarding xrdp, during my tests I got many errors from xrdp so I decided to kick xrdp and go back to vnc...

"`partx: /dev/loop0: error adding partitions 1-2`"
In this context, this message should be ignored, so I have now adapted the script accordingly.

As you can see you have now 2.4G freespace in your image
```
Filesystem          Size  Used    Avail   Use% Mounted on
/dev/loop0p1    545M   49M  497M   9%  /mnt/backup.img/boot
/dev/loop0p2      13G   9.4G  2.4G    80% /mnt/backup.img
```
You can now perform backups to this image until the space is “used up”. Subsequent backups only synchronize the differences between the source file system and the image. They are therefore considerably faster than the initial backup.

BTW: The size of the image can be set when creating the image: 
 `RaspiBackup.sh start -c -s xxxxx  BACKUPFILENAME`
where xxxxx is the size of the backupfile in Mb. You can find this information also in the  [readme.md](https://github.com/dolorosus/RaspiBackup/blob/master/Readme.md)

The next step would be to investigate why the ` -f` option is not supported on your system.  `parted -f` is necessary for a successful resizing of the image.

**Comment by JoostDkr** [comment]
Well Dolorosus,
Thanks for sharing your sofware. I will use, and test it.

**Comment by JoostDkr** [comment]
After a view times of succes. The proces fails :-(.
The command is "sudo ./scripts/RaspiBackup2.sh start -c /media/pi/rpi-backup/backup.img" 
On advance backup.img was deleted.
The result is: [RaspiBackup.txt](https://github.com/user-attachments/files/17263024/RaspiBackup.txt)
I have tried to find the reason. Not discovered....

**Comment by dolorosus** [comment]
If you use the `-c` option the backup file will (re)created.
If you want to refesh a backup don't use `-c` as it is described under 'Refresh of backup.img'  in the [readme.md](https://github.com/dolorosus/RaspiBackup/blob/master/Readme.md)

`./scripts/RaspiBackup.sh: line 285: --exclude=tmp/**: No such file or directory`
Are you sure you use an unaltered version of RaspiBackup.sh?

**Comment by JoostDkr** [comment]
Your are right. I altered your version.  Was searching for the cause of the  xrdp problem. I like to alter line 283 by remove the "--exclude" part. Maybe something is excluded that is important to xrdp. Is that a good try? When yes, can you tel me how to change line 282 for that purpose?

**Comment by JoostDkr** [comment]
I removed the exclude part in RaspiBackup.sh by changing line 283 in 
        rsync ${rsyncopt}  \
            / "${MOUNTDIR}"/
Unfortunately remote desktop still did not work..:-( and "systemctl is-active xrdp" results in "failed".

**Comment by dolorosus** [comment]
RaspiBackup.sh is OSS, which means it is open for you to test, modify, customize, or further develop the software to your personal needs. 
However, I kindly ask that you do not confuse Github Issues with a personal support forum. If you change something, you are responsible for your changes.

If you're having trouble with xrdp, it might be helpful to first identify the root cause of the issue before making any changes.
