### ISSUE TITLE
Tweaking rsync excludes

### ISSUE THREAD

**Issue by ephestione** [dolorosus/RaspiBackup#2]
As per [this](https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=230618&p=1544251#p1544251) you might want to add
`var/cache/apt/archives/`
in the excludes, and also change
`home/pi/.cache/`
to
home/${USERNAME}/.cache/
and define that parameter by default in the beginning of the script (most users will have totally removed user 'pi', and will have a single folder under /home/, which you can take the username from, and then maybe add a optarg to commandline to specify that... but maybe it would be overkill

**Comment by dolorosus** [comment]
Thanks, I added /var/cache/apt/archives/ to the exclusion list.

Gimmie some to time to think how to handle the username...

**Comment by dolorosus** [comment]
I think it would be better to exclude 
${HOME##/}/.cache/

**Comment by ephestione** [comment]
```
root@raspi3:/home/pi2pi# echo ${HOME##/}
root
```

In my case that wouldn't work, but `/home/*/.cache` seems to do the trick
